### ISSUE TITLE
VS Code update fails with "Access is denied."

### ISSUE THREAD

**Issue by TPMoyer** [ndabas/pico-setup-windows#22]
First off:   Thank you for writing this script.  Is WAY better than the many manual step alternative.

Small foible with the install.   After opening the command prompt which sets in place the environment, using Visual Studio Code, and closing same... Visual Studio tries to peek for and install updates.   This fails with
![VS Code Update Fail](https://user-images.githubusercontent.com/5302976/172429297-abbcbc44-757b-431b-a5ef-754adb3ee0e9.png)
 
How can I go in and change permissions
to what series of directories
to allow the updates to propagate through to success?

**Comment by DanielTomlinsonSage** [comment]
This might be a bit late, but in order to bypass this error you need to start VS Code as Administrator. 

![image](https://user-images.githubusercontent.com/23354408/180842072-81df72b7-4de7-4ce3-8163-dd139986bd81.png)

You can do this by:
- right-click on the shortcut in the task bar and,
- right-click again on the "Visual Studio Code" shortcut,
- selecting the "Run as Administrator" option.

Once launched you can check for updates under options and it should install any found without issue.

**Comment by DanielTomlinsonSage** [comment]
This issue can be closed.

**Comment by ndabas** [comment]
Thanks for documenting the issue and the fix! Closing.
