### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by EqUiNoX-Labs** [ndabas/pico-setup-windows#32]
Running the install of libraries at end of setup generated the following error...

Cloning into 'C:/Users/equin/OneDrive/Documents/Pico/picoprobe/freertos'...
git-lfs filter-process: line 1: git-lfs: command not found
fatal: the remote end hung up unexpectedly
fatal: Unable to checkout 'a65b7c9a3e6502127fdb80eb288d8cbdf251a6f4' in submodule path 'CMSIS_5'

Downloading and installing git-lfs from https://git-lfs.com/ then reinstalling gave me further issues as the pico folder still existed (may be good to detect it exists and offer to delete)

After deleting pico folder and re-installing it all worked fine, so maybe good to include git-lfs in your setup.

Thanks for the great project, i can see it being very useful

**Comment by ndabas** [comment]
Thanks for the kind words!

Regarding the issue that you saw, I'm not sure why you got that git-lfs error -- maybe you already had another installation of Git on your computer? git-lfs is already included in the git installer in the package.

In any case, that does not seem to have been the issue -- looks like `fatal: the remote end hung up unexpectedly` was what stopped it. That was most likely a transient network issue, so when you tried again, it worked.

We do check if the repo is checked out already, but then we leave it alone if it is -- because the user might have some in-progress work or be on another branch or something.
